const { analyzeFoodNutrition } = require('../src/server/geminiService');

let passedTests = 0;
let totalTests = 0;

function assert(condition, message) {
  totalTests++;
  if (condition) {
    console.log(`✅ Passed: ${message}`);
    passedTests++;
  } else {
    console.error(`❌ Failed: ${message}`);
    process.exitCode = 1;
  }
}

async function runTests() {
  console.log('\n================================================================');
  console.log('🥗 TESTING GOOGLE GEMINI VISION AI FOOD SUGGESTIONS & ANALYSIS');
  console.log('================================================================\n');

  // Small valid test JPEG base64
  const samplePhotoBase64 = 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////wgALCAABAAEBAREA/8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPxA=';

  // --- TEST 1: High-Protein Healthy Meal Photo Analysis ---
  console.log('--- TEST 1: High-Protein Healthy Meal Photo Analysis ---');
  const healthyResult = await analyzeFoodNutrition({
    imageBase64: samplePhotoBase64,
    mealDescription: 'Grilled salmon fillet with steamed brown rice, avocado, and baby spinach salad',
    userFitnessGoal: 'Muscle hypertrophy and strength recovery',
  });

  assert(healthyResult.mealName.length > 0, `Identified dish: "${healthyResult.mealName}"`);
  assert(healthyResult.totalCalories >= 400 && healthyResult.totalCalories <= 950, `Realistic calorie estimate: ${healthyResult.totalCalories} kcal`);
  assert(healthyResult.macros.proteinGrams >= 25, `Identified high protein content: ${healthyResult.macros.proteinGrams}g`);
  assert(healthyResult.macros.carbsGrams >= 20, `Identified carbs: ${healthyResult.macros.carbsGrams}g`);
  assert(healthyResult.macros.fatsGrams >= 10, `Identified healthy fats: ${healthyResult.macros.fatsGrams}g`);
  assert(healthyResult.quality === 'excellent' || healthyResult.quality === 'good', `Nutrition quality classified as high (got: ${healthyResult.quality})`);
  assert(healthyResult.healthScore >= 80, `High health score: ${healthyResult.healthScore}/100`);
  assert(healthyResult.geminiSuggestions.length > 30, 'Gemini generated thorough sports dietitian coaching suggestions');
  assert(healthyResult.healthySwaps && healthyResult.healthySwaps.length >= 1, `Generated actionable healthy adjustments (${healthyResult.healthySwaps.length} items)`);
  assert(healthyResult.isFallback === false, 'Analysis generated by LIVE Google Gemini AI model');
  console.log(`ℹ️ Gemini Suggestion: "${healthyResult.geminiSuggestions.slice(0, 120)}..."`);

  // --- TEST 2: High Saturated Fat / Junk Food Meal Photo Analysis ---
  console.log('\n--- TEST 2: High Saturated Fat / Poor Quality Food Photo Analysis ---');
  const junkResult = await analyzeFoodNutrition({
    imageBase64: samplePhotoBase64,
    mealDescription: 'Double cheeseburger with deep-fried french fries and regular cola',
    userFitnessGoal: 'Fat loss and clean cardiovascular health',
  });

  assert(junkResult.totalCalories >= 650, `Identified high calorie density: ${junkResult.totalCalories} kcal`);
  assert(junkResult.macros.fatsGrams >= 25, `Identified high fats: ${junkResult.macros.fatsGrams}g`);
  assert(junkResult.quality === 'poor' || junkResult.quality === 'moderate', `Flagged poor/moderate dietary quality (got: ${junkResult.quality})`);
  assert(junkResult.healthScore <= 60, `Health score reflects low nutrient density: ${junkResult.healthScore}/100`);
  assert(junkResult.healthySwaps && junkResult.healthySwaps.length >= 2, `Provides at least 2 healthy swaps (got: ${junkResult.healthySwaps.length})`);
  assert(junkResult.isFallback === false, 'Analysis generated by LIVE Google Gemini AI model');
  console.log(`ℹ️ Gemini Warning & Advice: "${junkResult.geminiSuggestions.slice(0, 120)}..."`);
  console.log(`ℹ️ Recommended Swaps: ${JSON.stringify(junkResult.healthySwaps)}`);

  // --- TEST 3: Traditional Regional Dish (Indian Thali) ---
  console.log('\n--- TEST 3: Traditional Indian Meal Analysis & Protein Optimization ---');
  const thaliResult = await analyzeFoodNutrition({
    mealDescription: '2 Roti, Paneer Butter Masala, Dal Makhani, Rice and Gulab Jamun',
    userFitnessGoal: 'Lean muscle building',
  });

  assert(thaliResult.mealName.length > 0, `Identified meal: "${thaliResult.mealName}"`);
  assert(thaliResult.foodItems && thaliResult.foodItems.length >= 2, `Identified constituent dishes (${thaliResult.foodItems.length} items)`);
  assert(thaliResult.macros.proteinGrams > 0, `Protein calculated: ${thaliResult.macros.proteinGrams}g`);
  assert(thaliResult.geminiSuggestions.length > 30, 'Gemini generated culturally relevant dietary coaching');
  assert(thaliResult.isFallback === false, 'Analysis generated by LIVE Google Gemini AI model');
  console.log(`ℹ️ Thali Food Items: ${thaliResult.foodItems.map(i => `${i.name} (${i.calories} kcal)`).join(', ')}`);

  console.log('\n================================================================');
  console.log(`🎉 ALL GEMINI FOOD & NUTRITION TESTS PASSED (${passedTests}/${totalTests})!`);
  console.log('================================================================\n');
}

runTests().catch((e) => {
  console.error('Fatal test error:', e);
  process.exit(1);
});
